# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


### ADMINS ###
alex = Admin.create(firstname: 'Alexander', lastname: 'Euler', email: 'alexandereuler@t-online.de', password: 'KBASD6asduhbajh3jkjsd98HHJAFj3jas', password_confirmation: 'KBASD6asduhbajh3jkjsd98HHJAFj3jas')
lennart = Admin.create(firstname: 'Lennart', lastname: 'Milatz', email: 'lennimilatz@web.de', password: 'KBASD6asduhbajh3jkjsd98HHJAFj3jas', password_confirmation: 'KBASD6asduhbajh3jkjsd98HHJAFj3jas')


### TAGS ###
tag1 = Tag.create(key: 'Technik')
tag2 = Tag.create(key: 'Material')
tag3 = Tag.create(key: 'Jahr')
tag4 = Tag.create(key: 'Künstler')
tag5 = Tag.create(key: 'Maße (mit Rahmen)')
tag7 = Tag.create(key: 'Maße (ohne Rahmen)')
tag6 = Tag.create(key: 'Gewicht')
tag8 = Tag.create(key: 'Signiert')


### OFFERS ###
offer1 = Offer.create( title: 'Hohes Venn im Herbst',
                       teaser: 'Dieses herbstliche Venn-Motiv Josef Thomas lässt sich problemlos in das Œuvre des Landschaftsmalers aus dem Aachener Raum einreihen. Die schwungvolle Pinselführung, kombiniert mit dem kräftigem Farbauftrag, verleihen diesem Gemälde eine einzigartige Struktur, die den stürmischen Charakter des Bildes verstärkt.',
                       infotext: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. ',
                       images: '',
                       thumbnail: '')
Offertag.create(value: 'Öl auf Hartfaserplatte', offer_id: 1, tag_id: 1, order_id: 1)
Offertag.create(value: '1969', offer_id: 1, tag_id: 3, order_id: 2)
Offertag.create(value: 'Josef Thoma', offer_id: 1, tag_id: 4, order_id: 3)
Offertag.create(value: '43 cm x 60,5 cm', offer_id: 1, tag_id: 7, order_id: 4)
Offertag.create(value: '57 cm x 74 cm', offer_id: 1, tag_id: 5, order_id: 5)
Offertag.create(value: 'u. R. J. Thoma 69', offer_id: 1, tag_id: 8, order_id: 6)



offer2 = Offer.create( title: 'Die Hütte am Waldrand',
                       teaser: 'Gefallts gegangen alt tat unbeirrt für. Bescheiden geheiratet flo schuchtern fur gru. Uns launischen gearbeitet angenommen verschwand vor dienstmagd. Gewachsen ein schwemmen kellnerin schwachen gro art kraftiger ernstlich. Er uberwunden brotkugeln eigentlich wo. Je bi schneider rausperte plaudernd sudwesten. Die nur polemisch geschickt geburstet naturlich hol ein. Bangigkeit wo bodenlosen drechslers hinstellte se jahreszeit leuchtturm. Brot ton hast bist man grob wohl gute nur.',
                       infotext: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. ',
                       images: '',
                       thumbnail: '')
Offertag.create(value: 'Öl auf Leinwand', offer_id: 2, tag_id: 1, order_id: 1)
Offertag.create(value: '20./21. Jahrhundert', offer_id: 2, tag_id: 3, order_id: 2)
Offertag.create(value: 'Unbestimmt', offer_id: 2, tag_id: 4, order_id: 3)
Offertag.create(value: '24 cm x 29 cm', offer_id: 2, tag_id: 5, order_id: 4)
Offertag.create(value: '13 cm x 18 cm', offer_id: 2, tag_id: 7, order_id: 5)
Offertag.create(value: 'u. L. unleserlich', offer_id: 2, tag_id: 8, order_id: 6)


offer3 = Offer.create( title: 'Amrum Dünen',
                       teaser: 'Die Dünen von Amrum sind in der Vergangenheit oft auf Leinwand gebannt worden. Selten jedoch gelang es einem Künstler so gut wie G.H. Degenhardt das stürmische Temperament der Nordsee festzuhalten. Sein moderner, minimalistischer Stil setzte neue Akzente in der Landschaftsmalerei des 20. Jahrhunderts. ',
                       infotext: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. ',
                       images: '',
                       thumbnail: '')
Offertag.create(value: 'Öl auf Leinwand', offer_id: 3, tag_id: 1, order_id: 1)
Offertag.create(value: '2. Hälfte 20. Jahrhundert', offer_id: 3, tag_id: 3, order_id: 2)
Offertag.create(value: 'G. H. Degenhardt', offer_id: 3, tag_id: 4, order_id: 3)
Offertag.create(value: '34 cm x 40,5 cm', offer_id: 3, tag_id: 5, order_id: 4)
Offertag.create(value: '24,5 cm x 30 cm', offer_id: 3, tag_id: 7, order_id: 5)
Offertag.create(value: 'u. L. monogrammiert GHD; Zertifikat', offer_id: 3, tag_id: 8, order_id: 6)


offer4 = Offer.create( title: 'Waldstück am See',
                       teaser: 'Albrecht Herrmanns Gespür für Farben spiegelt sich auch in diesem Ölgemälde des saarländischen Malers wieder. Die leuchtenden Rot- und Orangetöne der herbstlichen Waldlandschaft harmonieren perfekt mit den fast Violett- und Blautönen der Berge. Das Gemälde befindet sich in restaurationsbedürftigem Zustand. ',
                       infotext: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. ',
                       images: '',
                       thumbnail: '')
Offertag.create(value: 'Öl auf Leinwand', offer_id: 4, tag_id: 1, order_id: 1)
Offertag.create(value: '20. Jahrhundert', offer_id: 4, tag_id: 3, order_id: 2)
Offertag.create(value: 'Albrecht Herrmann', offer_id: 4, tag_id: 4, order_id: 3)
Offertag.create(value: '52 cm x 67 cm', offer_id: 4, tag_id: 5, order_id: 4)
Offertag.create(value: '41 cm x 56,5 cm', offer_id: 4, tag_id: 7, order_id: 5)
Offertag.create(value: 'u. R. A. Herrmann', offer_id: 4, tag_id: 8, order_id: 6)

offer5 = Offer.create( title: 'Schorte-Tal bei Illmenau in Thüringen',
                       teaser: 'Lässt man auf den Hügeln bei Illmenau den Blick schweifen, so entdeckt man vielleicht jenes malerische Tal, welches dieser leider unidentifiziert gebliebene Künstler im frühen 20. Jahrhundert mit seinen Ölfarben einfing. In nahezu impressionistischer Art und Weise gelang es dem Künstler, trotz oder gerade Dank der verschwimmenden Konturen, eine scharfe Momentaufnahme mitteldeutscher Landschaft festzuhalten. ',
                       infotext: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. ',
                       images: '',
                       thumbnail: '')
Offertag.create(value: 'Öl auf Platte', offer_id: 5, tag_id: 1, order_id: 1)
Offertag.create(value: 'Juli 1921', offer_id: 5, tag_id: 3, order_id: 2)
Offertag.create(value: 'Unbestimmt', offer_id: 5, tag_id: 4, order_id: 3)
Offertag.create(value: '38 cm x 57 cms', offer_id: 5, tag_id: 5, order_id: 4)
Offertag.create(value: 'u. R. unleserlich', offer_id: 5, tag_id: 8, order_id: 5)


post1 = Post.create(title: 'Post 1',
                    content: 'Bei der US-Wahl und beim Brexit-Referendum lagen Meinungsforscher dermaßen daneben, dass in der ZEIT-ONLINE-Redaktion eine Diskussion entbrannt ist, ob man Meinungsumfragen noch trauen darf. Und wenn nicht: Sollen wir überhaupt noch über sie berichten? Wir sind der Datenjournalist und der Bordmathematiker von ZEIT ONLINE und haben uns gemeinsam mit Kolleginnen und Kollegen vor der Bundestagswahl mit dieser Frage beschäftigt. Insbesondere bei knappen Entweder-Oder-Entscheidungen (wie Brexit und US-Wahl) ist der Aussagewert von Meinungsumfragen sehr beschränkt oder schlicht nicht vorhanden. Zwar unterscheidet sich das Wahlrecht bei der Bundestagswahl fundamental von dem der US-Präsidentschaftswahl; es geht bei uns eben nicht nur um zwei Kandidaten. Dennoch haben Wahlumfragen auch hier ihre Tücken. Dies beginnt schon damit, dass Wahlumfragen häufig für eine Prognose über den tatsächlichen Wahlausgang gehalten werden und auch entsprechend über sie berichtet wird. In Wahrheit sind Wahlumfragen Momentaufnahmen. Sie geben ein eingeschränktes Stimmungsbild wieder. Ohnehin ist die schiere Anzahl der Wahlumfragen insbesondere jetzt, kurz vor der Bundestagswahl, enorm. Meinungsforschungsinstitute veröffentlichen laufend neue Zahlen, zum Teil sogar mehrmals in der Woche. Die hohe Taktung von immer neuen Umfragen erzeugt leicht den Eindruck, der Wahlkampf gleiche einem Rennen. Wieder hat eine Partei einen Prozentpunkt hinzu gewonnen und liegt nun knapp vor der Konkurrenz. Doch tut sie es wirklich? Man kann das nicht so präzise sagen, wie es die Umfrageergebnisse scheinen lassen. Wer die Möglichkeiten und Methoden der Demoskopie genau betrachtet, erkennt, dass solch scheinbar punktgenaue Aussagen anhand einer einzelnen Wahlumfrage gar nicht getroffen werden können. Bei ZEIT ONLINE wollen wir deshalb mit derartigen Meldungen zurückhaltend sein. Die vermeintliche Nachricht, wonach Partei X einen oder zwei Prozentpunkte hinzugewonnen habe, werden Sie bei uns nicht mehr finden. Umfrageergebnisse unterliegen immer Fehlern, denn sie basieren auf Stichprobenbefragungen. Diese Befragungen erreichen aber in der Regel nur spezielle Teile der Bevölkerung, beispielsweise Menschen mit Festnetztelefonanschluss oder Internetnutzer. Einige Teilnehmer antworten obendrein falsch. Oder sie reagieren auf vorangegangene Umfragen und Publikationen. Das heißt, sie antworten nicht, was sie meinen; sie antworten mit Erwartungen. Natürlich wissen Umfrageinstitute das sehr genau. Um dennoch ein allgemeines Meinungsbild über alle Bevölkerungsgruppen hinweg berechnen zu können, gleichen die Demoskopen vermutete Einflüsse aus und gewichten die vorliegenden Zahlen. Die Rezepte dafür unterscheiden sich von Institut zu Institut. Sie sind so geheim wie die Colaformel.',
                    teaser_content: 'Bei der US-Wahl und beim Brexit-Referendum lagen Meinungsforscher dermaßen daneben, dass in der ZEIT-ONLINE-Redaktion eine Diskussion entbrannt ist, ob man Meinungsumfragen noch trauen darf. Und wenn nicht: Sollen wir überhaupt noch über sie berichten? ',
                    offer: '1',
                    published: '1')
post2 = Post.create(title: 'Post 2',
                    content: 'Bei der US-Wahl und beim Brexit-Referendum lagen Meinungsforscher dermaßen daneben, dass in der ZEIT-ONLINE-Redaktion eine Diskussion entbrannt ist, ob man Meinungsumfragen noch trauen darf. Und wenn nicht: Sollen wir überhaupt noch über sie berichten? Wir sind der Datenjournalist und der Bordmathematiker von ZEIT ONLINE und haben uns gemeinsam mit Kolleginnen und Kollegen vor der Bundestagswahl mit dieser Frage beschäftigt. Insbesondere bei knappen Entweder-Oder-Entscheidungen (wie Brexit und US-Wahl) ist der Aussagewert von Meinungsumfragen sehr beschränkt oder schlicht nicht vorhanden. Zwar unterscheidet sich das Wahlrecht bei der Bundestagswahl fundamental von dem der US-Präsidentschaftswahl; es geht bei uns eben nicht nur um zwei Kandidaten. Dennoch haben Wahlumfragen auch hier ihre Tücken. Dies beginnt schon damit, dass Wahlumfragen häufig für eine Prognose über den tatsächlichen Wahlausgang gehalten werden und auch entsprechend über sie berichtet wird. In Wahrheit sind Wahlumfragen Momentaufnahmen. Sie geben ein eingeschränktes Stimmungsbild wieder. Ohnehin ist die schiere Anzahl der Wahlumfragen insbesondere jetzt, kurz vor der Bundestagswahl, enorm. Meinungsforschungsinstitute veröffentlichen laufend neue Zahlen, zum Teil sogar mehrmals in der Woche. Die hohe Taktung von immer neuen Umfragen erzeugt leicht den Eindruck, der Wahlkampf gleiche einem Rennen. Wieder hat eine Partei einen Prozentpunkt hinzu gewonnen und liegt nun knapp vor der Konkurrenz. Doch tut sie es wirklich? Man kann das nicht so präzise sagen, wie es die Umfrageergebnisse scheinen lassen. Wer die Möglichkeiten und Methoden der Demoskopie genau betrachtet, erkennt, dass solch scheinbar punktgenaue Aussagen anhand einer einzelnen Wahlumfrage gar nicht getroffen werden können. Bei ZEIT ONLINE wollen wir deshalb mit derartigen Meldungen zurückhaltend sein. Die vermeintliche Nachricht, wonach Partei X einen oder zwei Prozentpunkte hinzugewonnen habe, werden Sie bei uns nicht mehr finden. Umfrageergebnisse unterliegen immer Fehlern, denn sie basieren auf Stichprobenbefragungen. Diese Befragungen erreichen aber in der Regel nur spezielle Teile der Bevölkerung, beispielsweise Menschen mit Festnetztelefonanschluss oder Internetnutzer. Einige Teilnehmer antworten obendrein falsch. Oder sie reagieren auf vorangegangene Umfragen und Publikationen. Das heißt, sie antworten nicht, was sie meinen; sie antworten mit Erwartungen. Natürlich wissen Umfrageinstitute das sehr genau. Um dennoch ein allgemeines Meinungsbild über alle Bevölkerungsgruppen hinweg berechnen zu können, gleichen die Demoskopen vermutete Einflüsse aus und gewichten die vorliegenden Zahlen. Die Rezepte dafür unterscheiden sich von Institut zu Institut. Sie sind so geheim wie die Colaformel.',
                    teaser_content: 'Bei der US-Wahl und beim Brexit-Referendum lagen Meinungsforscher dermaßen daneben, dass in der ZEIT-ONLINE-Redaktion eine Diskussion entbrannt ist, ob man Meinungsumfragen noch trauen darf. Und wenn nicht: Sollen wir überhaupt noch über sie berichten? ',
                    offer: '1',
                    published: '1')
post3 = Post.create(title: 'Post 3',
                    content: 'Bei der US-Wahl und beim Brexit-Referendum lagen Meinungsforscher dermaßen daneben, dass in der ZEIT-ONLINE-Redaktion eine Diskussion entbrannt ist, ob man Meinungsumfragen noch trauen darf. Und wenn nicht: Sollen wir überhaupt noch über sie berichten? Wir sind der Datenjournalist und der Bordmathematiker von ZEIT ONLINE und haben uns gemeinsam mit Kolleginnen und Kollegen vor der Bundestagswahl mit dieser Frage beschäftigt. Insbesondere bei knappen Entweder-Oder-Entscheidungen (wie Brexit und US-Wahl) ist der Aussagewert von Meinungsumfragen sehr beschränkt oder schlicht nicht vorhanden. Zwar unterscheidet sich das Wahlrecht bei der Bundestagswahl fundamental von dem der US-Präsidentschaftswahl; es geht bei uns eben nicht nur um zwei Kandidaten. Dennoch haben Wahlumfragen auch hier ihre Tücken. Dies beginnt schon damit, dass Wahlumfragen häufig für eine Prognose über den tatsächlichen Wahlausgang gehalten werden und auch entsprechend über sie berichtet wird. In Wahrheit sind Wahlumfragen Momentaufnahmen. Sie geben ein eingeschränktes Stimmungsbild wieder. Ohnehin ist die schiere Anzahl der Wahlumfragen insbesondere jetzt, kurz vor der Bundestagswahl, enorm. Meinungsforschungsinstitute veröffentlichen laufend neue Zahlen, zum Teil sogar mehrmals in der Woche. Die hohe Taktung von immer neuen Umfragen erzeugt leicht den Eindruck, der Wahlkampf gleiche einem Rennen. Wieder hat eine Partei einen Prozentpunkt hinzu gewonnen und liegt nun knapp vor der Konkurrenz. Doch tut sie es wirklich? Man kann das nicht so präzise sagen, wie es die Umfrageergebnisse scheinen lassen. Wer die Möglichkeiten und Methoden der Demoskopie genau betrachtet, erkennt, dass solch scheinbar punktgenaue Aussagen anhand einer einzelnen Wahlumfrage gar nicht getroffen werden können. Bei ZEIT ONLINE wollen wir deshalb mit derartigen Meldungen zurückhaltend sein. Die vermeintliche Nachricht, wonach Partei X einen oder zwei Prozentpunkte hinzugewonnen habe, werden Sie bei uns nicht mehr finden. Umfrageergebnisse unterliegen immer Fehlern, denn sie basieren auf Stichprobenbefragungen. Diese Befragungen erreichen aber in der Regel nur spezielle Teile der Bevölkerung, beispielsweise Menschen mit Festnetztelefonanschluss oder Internetnutzer. Einige Teilnehmer antworten obendrein falsch. Oder sie reagieren auf vorangegangene Umfragen und Publikationen. Das heißt, sie antworten nicht, was sie meinen; sie antworten mit Erwartungen. Natürlich wissen Umfrageinstitute das sehr genau. Um dennoch ein allgemeines Meinungsbild über alle Bevölkerungsgruppen hinweg berechnen zu können, gleichen die Demoskopen vermutete Einflüsse aus und gewichten die vorliegenden Zahlen. Die Rezepte dafür unterscheiden sich von Institut zu Institut. Sie sind so geheim wie die Colaformel.',
                    teaser_content: 'Bei der US-Wahl und beim Brexit-Referendum lagen Meinungsforscher dermaßen daneben, dass in der ZEIT-ONLINE-Redaktion eine Diskussion entbrannt ist, ob man Meinungsumfragen noch trauen darf. Und wenn nicht: Sollen wir überhaupt noch über sie berichten? ',
                    offer: '1',
                    published: '1')
post4 = Post.create(title: 'Post 4',
                    content: 'Bei der US-Wahl und beim Brexit-Referendum lagen Meinungsforscher dermaßen daneben, dass in der ZEIT-ONLINE-Redaktion eine Diskussion entbrannt ist, ob man Meinungsumfragen noch trauen darf. Und wenn nicht: Sollen wir überhaupt noch über sie berichten? Wir sind der Datenjournalist und der Bordmathematiker von ZEIT ONLINE und haben uns gemeinsam mit Kolleginnen und Kollegen vor der Bundestagswahl mit dieser Frage beschäftigt. Insbesondere bei knappen Entweder-Oder-Entscheidungen (wie Brexit und US-Wahl) ist der Aussagewert von Meinungsumfragen sehr beschränkt oder schlicht nicht vorhanden. Zwar unterscheidet sich das Wahlrecht bei der Bundestagswahl fundamental von dem der US-Präsidentschaftswahl; es geht bei uns eben nicht nur um zwei Kandidaten. Dennoch haben Wahlumfragen auch hier ihre Tücken. Dies beginnt schon damit, dass Wahlumfragen häufig für eine Prognose über den tatsächlichen Wahlausgang gehalten werden und auch entsprechend über sie berichtet wird. In Wahrheit sind Wahlumfragen Momentaufnahmen. Sie geben ein eingeschränktes Stimmungsbild wieder. Ohnehin ist die schiere Anzahl der Wahlumfragen insbesondere jetzt, kurz vor der Bundestagswahl, enorm. Meinungsforschungsinstitute veröffentlichen laufend neue Zahlen, zum Teil sogar mehrmals in der Woche. Die hohe Taktung von immer neuen Umfragen erzeugt leicht den Eindruck, der Wahlkampf gleiche einem Rennen. Wieder hat eine Partei einen Prozentpunkt hinzu gewonnen und liegt nun knapp vor der Konkurrenz. Doch tut sie es wirklich? Man kann das nicht so präzise sagen, wie es die Umfrageergebnisse scheinen lassen. Wer die Möglichkeiten und Methoden der Demoskopie genau betrachtet, erkennt, dass solch scheinbar punktgenaue Aussagen anhand einer einzelnen Wahlumfrage gar nicht getroffen werden können. Bei ZEIT ONLINE wollen wir deshalb mit derartigen Meldungen zurückhaltend sein. Die vermeintliche Nachricht, wonach Partei X einen oder zwei Prozentpunkte hinzugewonnen habe, werden Sie bei uns nicht mehr finden. Umfrageergebnisse unterliegen immer Fehlern, denn sie basieren auf Stichprobenbefragungen. Diese Befragungen erreichen aber in der Regel nur spezielle Teile der Bevölkerung, beispielsweise Menschen mit Festnetztelefonanschluss oder Internetnutzer. Einige Teilnehmer antworten obendrein falsch. Oder sie reagieren auf vorangegangene Umfragen und Publikationen. Das heißt, sie antworten nicht, was sie meinen; sie antworten mit Erwartungen. Natürlich wissen Umfrageinstitute das sehr genau. Um dennoch ein allgemeines Meinungsbild über alle Bevölkerungsgruppen hinweg berechnen zu können, gleichen die Demoskopen vermutete Einflüsse aus und gewichten die vorliegenden Zahlen. Die Rezepte dafür unterscheiden sich von Institut zu Institut. Sie sind so geheim wie die Colaformel.',
                    teaser_content: 'Bei der US-Wahl und beim Brexit-Referendum lagen Meinungsforscher dermaßen daneben, dass in der ZEIT-ONLINE-Redaktion eine Diskussion entbrannt ist, ob man Meinungsumfragen noch trauen darf. Und wenn nicht: Sollen wir überhaupt noch über sie berichten? ',
                    offer: '1',
                    published: '1')
post5 = Post.create(title: 'Post 5',
                    content: 'Bei der US-Wahl und beim Brexit-Referendum lagen Meinungsforscher dermaßen daneben, dass in der ZEIT-ONLINE-Redaktion eine Diskussion entbrannt ist, ob man Meinungsumfragen noch trauen darf. Und wenn nicht: Sollen wir überhaupt noch über sie berichten? Wir sind der Datenjournalist und der Bordmathematiker von ZEIT ONLINE und haben uns gemeinsam mit Kolleginnen und Kollegen vor der Bundestagswahl mit dieser Frage beschäftigt. Insbesondere bei knappen Entweder-Oder-Entscheidungen (wie Brexit und US-Wahl) ist der Aussagewert von Meinungsumfragen sehr beschränkt oder schlicht nicht vorhanden. Zwar unterscheidet sich das Wahlrecht bei der Bundestagswahl fundamental von dem der US-Präsidentschaftswahl; es geht bei uns eben nicht nur um zwei Kandidaten. Dennoch haben Wahlumfragen auch hier ihre Tücken. Dies beginnt schon damit, dass Wahlumfragen häufig für eine Prognose über den tatsächlichen Wahlausgang gehalten werden und auch entsprechend über sie berichtet wird. In Wahrheit sind Wahlumfragen Momentaufnahmen. Sie geben ein eingeschränktes Stimmungsbild wieder. Ohnehin ist die schiere Anzahl der Wahlumfragen insbesondere jetzt, kurz vor der Bundestagswahl, enorm. Meinungsforschungsinstitute veröffentlichen laufend neue Zahlen, zum Teil sogar mehrmals in der Woche. Die hohe Taktung von immer neuen Umfragen erzeugt leicht den Eindruck, der Wahlkampf gleiche einem Rennen. Wieder hat eine Partei einen Prozentpunkt hinzu gewonnen und liegt nun knapp vor der Konkurrenz. Doch tut sie es wirklich? Man kann das nicht so präzise sagen, wie es die Umfrageergebnisse scheinen lassen. Wer die Möglichkeiten und Methoden der Demoskopie genau betrachtet, erkennt, dass solch scheinbar punktgenaue Aussagen anhand einer einzelnen Wahlumfrage gar nicht getroffen werden können. Bei ZEIT ONLINE wollen wir deshalb mit derartigen Meldungen zurückhaltend sein. Die vermeintliche Nachricht, wonach Partei X einen oder zwei Prozentpunkte hinzugewonnen habe, werden Sie bei uns nicht mehr finden. Umfrageergebnisse unterliegen immer Fehlern, denn sie basieren auf Stichprobenbefragungen. Diese Befragungen erreichen aber in der Regel nur spezielle Teile der Bevölkerung, beispielsweise Menschen mit Festnetztelefonanschluss oder Internetnutzer. Einige Teilnehmer antworten obendrein falsch. Oder sie reagieren auf vorangegangene Umfragen und Publikationen. Das heißt, sie antworten nicht, was sie meinen; sie antworten mit Erwartungen. Natürlich wissen Umfrageinstitute das sehr genau. Um dennoch ein allgemeines Meinungsbild über alle Bevölkerungsgruppen hinweg berechnen zu können, gleichen die Demoskopen vermutete Einflüsse aus und gewichten die vorliegenden Zahlen. Die Rezepte dafür unterscheiden sich von Institut zu Institut. Sie sind so geheim wie die Colaformel.',
                    teaser_content: 'Bei der US-Wahl und beim Brexit-Referendum lagen Meinungsforscher dermaßen daneben, dass in der ZEIT-ONLINE-Redaktion eine Diskussion entbrannt ist, ob man Meinungsumfragen noch trauen darf. Und wenn nicht: Sollen wir überhaupt noch über sie berichten? ',
                    offer: '1',
                    published: '1')
post6 = Post.create(title: 'Post 6',
                    content: 'Bei der US-Wahl und beim Brexit-Referendum lagen Meinungsforscher dermaßen daneben, dass in der ZEIT-ONLINE-Redaktion eine Diskussion entbrannt ist, ob man Meinungsumfragen noch trauen darf. Und wenn nicht: Sollen wir überhaupt noch über sie berichten? Wir sind der Datenjournalist und der Bordmathematiker von ZEIT ONLINE und haben uns gemeinsam mit Kolleginnen und Kollegen vor der Bundestagswahl mit dieser Frage beschäftigt. Insbesondere bei knappen Entweder-Oder-Entscheidungen (wie Brexit und US-Wahl) ist der Aussagewert von Meinungsumfragen sehr beschränkt oder schlicht nicht vorhanden. Zwar unterscheidet sich das Wahlrecht bei der Bundestagswahl fundamental von dem der US-Präsidentschaftswahl; es geht bei uns eben nicht nur um zwei Kandidaten. Dennoch haben Wahlumfragen auch hier ihre Tücken. Dies beginnt schon damit, dass Wahlumfragen häufig für eine Prognose über den tatsächlichen Wahlausgang gehalten werden und auch entsprechend über sie berichtet wird. In Wahrheit sind Wahlumfragen Momentaufnahmen. Sie geben ein eingeschränktes Stimmungsbild wieder. Ohnehin ist die schiere Anzahl der Wahlumfragen insbesondere jetzt, kurz vor der Bundestagswahl, enorm. Meinungsforschungsinstitute veröffentlichen laufend neue Zahlen, zum Teil sogar mehrmals in der Woche. Die hohe Taktung von immer neuen Umfragen erzeugt leicht den Eindruck, der Wahlkampf gleiche einem Rennen. Wieder hat eine Partei einen Prozentpunkt hinzu gewonnen und liegt nun knapp vor der Konkurrenz. Doch tut sie es wirklich? Man kann das nicht so präzise sagen, wie es die Umfrageergebnisse scheinen lassen. Wer die Möglichkeiten und Methoden der Demoskopie genau betrachtet, erkennt, dass solch scheinbar punktgenaue Aussagen anhand einer einzelnen Wahlumfrage gar nicht getroffen werden können. Bei ZEIT ONLINE wollen wir deshalb mit derartigen Meldungen zurückhaltend sein. Die vermeintliche Nachricht, wonach Partei X einen oder zwei Prozentpunkte hinzugewonnen habe, werden Sie bei uns nicht mehr finden. Umfrageergebnisse unterliegen immer Fehlern, denn sie basieren auf Stichprobenbefragungen. Diese Befragungen erreichen aber in der Regel nur spezielle Teile der Bevölkerung, beispielsweise Menschen mit Festnetztelefonanschluss oder Internetnutzer. Einige Teilnehmer antworten obendrein falsch. Oder sie reagieren auf vorangegangene Umfragen und Publikationen. Das heißt, sie antworten nicht, was sie meinen; sie antworten mit Erwartungen. Natürlich wissen Umfrageinstitute das sehr genau. Um dennoch ein allgemeines Meinungsbild über alle Bevölkerungsgruppen hinweg berechnen zu können, gleichen die Demoskopen vermutete Einflüsse aus und gewichten die vorliegenden Zahlen. Die Rezepte dafür unterscheiden sich von Institut zu Institut. Sie sind so geheim wie die Colaformel.',
                    teaser_content: 'Bei der US-Wahl und beim Brexit-Referendum lagen Meinungsforscher dermaßen daneben, dass in der ZEIT-ONLINE-Redaktion eine Diskussion entbrannt ist, ob man Meinungsumfragen noch trauen darf. Und wenn nicht: Sollen wir überhaupt noch über sie berichten? ',
                    offer: '1',
                    published: '1')
post7 = Post.create(title: 'Post 7',
                    content: 'Bei der US-Wahl und beim Brexit-Referendum lagen Meinungsforscher dermaßen daneben, dass in der ZEIT-ONLINE-Redaktion eine Diskussion entbrannt ist, ob man Meinungsumfragen noch trauen darf. Und wenn nicht: Sollen wir überhaupt noch über sie berichten? Wir sind der Datenjournalist und der Bordmathematiker von ZEIT ONLINE und haben uns gemeinsam mit Kolleginnen und Kollegen vor der Bundestagswahl mit dieser Frage beschäftigt. Insbesondere bei knappen Entweder-Oder-Entscheidungen (wie Brexit und US-Wahl) ist der Aussagewert von Meinungsumfragen sehr beschränkt oder schlicht nicht vorhanden. Zwar unterscheidet sich das Wahlrecht bei der Bundestagswahl fundamental von dem der US-Präsidentschaftswahl; es geht bei uns eben nicht nur um zwei Kandidaten. Dennoch haben Wahlumfragen auch hier ihre Tücken. Dies beginnt schon damit, dass Wahlumfragen häufig für eine Prognose über den tatsächlichen Wahlausgang gehalten werden und auch entsprechend über sie berichtet wird. In Wahrheit sind Wahlumfragen Momentaufnahmen. Sie geben ein eingeschränktes Stimmungsbild wieder. Ohnehin ist die schiere Anzahl der Wahlumfragen insbesondere jetzt, kurz vor der Bundestagswahl, enorm. Meinungsforschungsinstitute veröffentlichen laufend neue Zahlen, zum Teil sogar mehrmals in der Woche. Die hohe Taktung von immer neuen Umfragen erzeugt leicht den Eindruck, der Wahlkampf gleiche einem Rennen. Wieder hat eine Partei einen Prozentpunkt hinzu gewonnen und liegt nun knapp vor der Konkurrenz. Doch tut sie es wirklich? Man kann das nicht so präzise sagen, wie es die Umfrageergebnisse scheinen lassen. Wer die Möglichkeiten und Methoden der Demoskopie genau betrachtet, erkennt, dass solch scheinbar punktgenaue Aussagen anhand einer einzelnen Wahlumfrage gar nicht getroffen werden können. Bei ZEIT ONLINE wollen wir deshalb mit derartigen Meldungen zurückhaltend sein. Die vermeintliche Nachricht, wonach Partei X einen oder zwei Prozentpunkte hinzugewonnen habe, werden Sie bei uns nicht mehr finden. Umfrageergebnisse unterliegen immer Fehlern, denn sie basieren auf Stichprobenbefragungen. Diese Befragungen erreichen aber in der Regel nur spezielle Teile der Bevölkerung, beispielsweise Menschen mit Festnetztelefonanschluss oder Internetnutzer. Einige Teilnehmer antworten obendrein falsch. Oder sie reagieren auf vorangegangene Umfragen und Publikationen. Das heißt, sie antworten nicht, was sie meinen; sie antworten mit Erwartungen. Natürlich wissen Umfrageinstitute das sehr genau. Um dennoch ein allgemeines Meinungsbild über alle Bevölkerungsgruppen hinweg berechnen zu können, gleichen die Demoskopen vermutete Einflüsse aus und gewichten die vorliegenden Zahlen. Die Rezepte dafür unterscheiden sich von Institut zu Institut. Sie sind so geheim wie die Colaformel.',
                    teaser_content: 'Bei der US-Wahl und beim Brexit-Referendum lagen Meinungsforscher dermaßen daneben, dass in der ZEIT-ONLINE-Redaktion eine Diskussion entbrannt ist, ob man Meinungsumfragen noch trauen darf. Und wenn nicht: Sollen wir überhaupt noch über sie berichten? ',
                    offer: '1',
                    published: '1')
post8 = Post.create(title: 'Post 8',
                    content: 'Bei der US-Wahl und beim Brexit-Referendum lagen Meinungsforscher dermaßen daneben, dass in der ZEIT-ONLINE-Redaktion eine Diskussion entbrannt ist, ob man Meinungsumfragen noch trauen darf. Und wenn nicht: Sollen wir überhaupt noch über sie berichten? Wir sind der Datenjournalist und der Bordmathematiker von ZEIT ONLINE und haben uns gemeinsam mit Kolleginnen und Kollegen vor der Bundestagswahl mit dieser Frage beschäftigt. Insbesondere bei knappen Entweder-Oder-Entscheidungen (wie Brexit und US-Wahl) ist der Aussagewert von Meinungsumfragen sehr beschränkt oder schlicht nicht vorhanden. Zwar unterscheidet sich das Wahlrecht bei der Bundestagswahl fundamental von dem der US-Präsidentschaftswahl; es geht bei uns eben nicht nur um zwei Kandidaten. Dennoch haben Wahlumfragen auch hier ihre Tücken. Dies beginnt schon damit, dass Wahlumfragen häufig für eine Prognose über den tatsächlichen Wahlausgang gehalten werden und auch entsprechend über sie berichtet wird. In Wahrheit sind Wahlumfragen Momentaufnahmen. Sie geben ein eingeschränktes Stimmungsbild wieder. Ohnehin ist die schiere Anzahl der Wahlumfragen insbesondere jetzt, kurz vor der Bundestagswahl, enorm. Meinungsforschungsinstitute veröffentlichen laufend neue Zahlen, zum Teil sogar mehrmals in der Woche. Die hohe Taktung von immer neuen Umfragen erzeugt leicht den Eindruck, der Wahlkampf gleiche einem Rennen. Wieder hat eine Partei einen Prozentpunkt hinzu gewonnen und liegt nun knapp vor der Konkurrenz. Doch tut sie es wirklich? Man kann das nicht so präzise sagen, wie es die Umfrageergebnisse scheinen lassen. Wer die Möglichkeiten und Methoden der Demoskopie genau betrachtet, erkennt, dass solch scheinbar punktgenaue Aussagen anhand einer einzelnen Wahlumfrage gar nicht getroffen werden können. Bei ZEIT ONLINE wollen wir deshalb mit derartigen Meldungen zurückhaltend sein. Die vermeintliche Nachricht, wonach Partei X einen oder zwei Prozentpunkte hinzugewonnen habe, werden Sie bei uns nicht mehr finden. Umfrageergebnisse unterliegen immer Fehlern, denn sie basieren auf Stichprobenbefragungen. Diese Befragungen erreichen aber in der Regel nur spezielle Teile der Bevölkerung, beispielsweise Menschen mit Festnetztelefonanschluss oder Internetnutzer. Einige Teilnehmer antworten obendrein falsch. Oder sie reagieren auf vorangegangene Umfragen und Publikationen. Das heißt, sie antworten nicht, was sie meinen; sie antworten mit Erwartungen. Natürlich wissen Umfrageinstitute das sehr genau. Um dennoch ein allgemeines Meinungsbild über alle Bevölkerungsgruppen hinweg berechnen zu können, gleichen die Demoskopen vermutete Einflüsse aus und gewichten die vorliegenden Zahlen. Die Rezepte dafür unterscheiden sich von Institut zu Institut. Sie sind so geheim wie die Colaformel.',
                    teaser_content: 'Bei der US-Wahl und beim Brexit-Referendum lagen Meinungsforscher dermaßen daneben, dass in der ZEIT-ONLINE-Redaktion eine Diskussion entbrannt ist, ob man Meinungsumfragen noch trauen darf. Und wenn nicht: Sollen wir überhaupt noch über sie berichten? ',
                    offer: '1',
                    published: '1')
post9 = Post.create(title: 'Post 9',
                    content: 'Bei der US-Wahl und beim Brexit-Referendum lagen Meinungsforscher dermaßen daneben, dass in der ZEIT-ONLINE-Redaktion eine Diskussion entbrannt ist, ob man Meinungsumfragen noch trauen darf. Und wenn nicht: Sollen wir überhaupt noch über sie berichten? Wir sind der Datenjournalist und der Bordmathematiker von ZEIT ONLINE und haben uns gemeinsam mit Kolleginnen und Kollegen vor der Bundestagswahl mit dieser Frage beschäftigt. Insbesondere bei knappen Entweder-Oder-Entscheidungen (wie Brexit und US-Wahl) ist der Aussagewert von Meinungsumfragen sehr beschränkt oder schlicht nicht vorhanden. Zwar unterscheidet sich das Wahlrecht bei der Bundestagswahl fundamental von dem der US-Präsidentschaftswahl; es geht bei uns eben nicht nur um zwei Kandidaten. Dennoch haben Wahlumfragen auch hier ihre Tücken. Dies beginnt schon damit, dass Wahlumfragen häufig für eine Prognose über den tatsächlichen Wahlausgang gehalten werden und auch entsprechend über sie berichtet wird. In Wahrheit sind Wahlumfragen Momentaufnahmen. Sie geben ein eingeschränktes Stimmungsbild wieder. Ohnehin ist die schiere Anzahl der Wahlumfragen insbesondere jetzt, kurz vor der Bundestagswahl, enorm. Meinungsforschungsinstitute veröffentlichen laufend neue Zahlen, zum Teil sogar mehrmals in der Woche. Die hohe Taktung von immer neuen Umfragen erzeugt leicht den Eindruck, der Wahlkampf gleiche einem Rennen. Wieder hat eine Partei einen Prozentpunkt hinzu gewonnen und liegt nun knapp vor der Konkurrenz. Doch tut sie es wirklich? Man kann das nicht so präzise sagen, wie es die Umfrageergebnisse scheinen lassen. Wer die Möglichkeiten und Methoden der Demoskopie genau betrachtet, erkennt, dass solch scheinbar punktgenaue Aussagen anhand einer einzelnen Wahlumfrage gar nicht getroffen werden können. Bei ZEIT ONLINE wollen wir deshalb mit derartigen Meldungen zurückhaltend sein. Die vermeintliche Nachricht, wonach Partei X einen oder zwei Prozentpunkte hinzugewonnen habe, werden Sie bei uns nicht mehr finden. Umfrageergebnisse unterliegen immer Fehlern, denn sie basieren auf Stichprobenbefragungen. Diese Befragungen erreichen aber in der Regel nur spezielle Teile der Bevölkerung, beispielsweise Menschen mit Festnetztelefonanschluss oder Internetnutzer. Einige Teilnehmer antworten obendrein falsch. Oder sie reagieren auf vorangegangene Umfragen und Publikationen. Das heißt, sie antworten nicht, was sie meinen; sie antworten mit Erwartungen. Natürlich wissen Umfrageinstitute das sehr genau. Um dennoch ein allgemeines Meinungsbild über alle Bevölkerungsgruppen hinweg berechnen zu können, gleichen die Demoskopen vermutete Einflüsse aus und gewichten die vorliegenden Zahlen. Die Rezepte dafür unterscheiden sich von Institut zu Institut. Sie sind so geheim wie die Colaformel.',
                    teaser_content: 'Bei der US-Wahl und beim Brexit-Referendum lagen Meinungsforscher dermaßen daneben, dass in der ZEIT-ONLINE-Redaktion eine Diskussion entbrannt ist, ob man Meinungsumfragen noch trauen darf. Und wenn nicht: Sollen wir überhaupt noch über sie berichten? ',
                    offer: '1',
                    published: '1')